on:
  workflow_call:
    inputs:
      target_branch:
        required: false
        type: string        
      publish_types:
        required: false
        default: false
        type: boolean
    
jobs:
  release:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          
      - if: ${{ inputs.target_branch != '' }}
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.target_branch }}

      - if: ${{ inputs.target_branch == '' }}
        uses: actions/checkout@v6

      - name: Get package info
        id: package-info
        uses: luizfelipelaviola/get-package-info@v2
        with:
          path: .

      - name: Install dependencies
        run: npm ci

      - name: Generate types
        if: ${{ inputs.publish_types }}
        run: npm run types
      
      - name: Create build
        run: npx @vscode/vsce package --allow-package-all-secrets
        
      - name: Upload build
        id: vsix-upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.package-info.outputs.name }}-pr-build
          path: ./*.vsix

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: new build is available

      - name: Post comment
        if: steps.fc.outputs.comment-id == '' && always()
        continue-on-error: true
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 A new build is available for this PR based on ${{ github.event.pull_request.head.sha }}.\n * [Download here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.vsix-upload.outputs.artifact-id }})\n* [Read more about how to test](https://github.com/codefori/.github/blob/main/.github/pr_testing_template.md)'            })

      - name: Update comment
        if: steps.fc.outputs.comment-id != '' && always()
        continue-on-error: true
        uses: peter-evans/create-or-update-comment@v1
        with:
          edit-mode: replace
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            👋 A new build is available for this PR based on ${{ github.event.pull_request.head.sha }}.

            * [Download here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.vsix-upload.outputs.artifact-id }})
            * [Read more about how to test](https://github.com/codefori/.github/blob/main/.github/pr_testing_template.md)
