on:
  workflow_call:
    inputs:   
      publish_types:
        required: false
        default: false
        type: boolean
    
jobs:
  release:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 24
        uses: actions/setup-node@v3
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout PR branch
        if: github.event.pull_request
        uses: actions/checkout@v6
        
      - name: Check PR comment
        if: github.event.issue.pull_request
        uses: khan/pull-request-comment-trigger@v1.1.0
        id: check-comment
        with:
          trigger: '/build'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Get PR branch
        if: steps.check-comment.outputs.triggered == 'true'
        uses: xt0rted/pull-request-comment-branch@v3
        id: comment-branch

      - name: Checkout PR branch from comment
        if: steps.comment-branch.outputs.head_ref != ''
        uses: actions/checkout@v6
        with:
          repo: ${{ steps.comment-branch.outputs.head_repo }}
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Get package info
        id: package-info
        uses: luizfelipelaviola/get-package-info@v2
        with:
          path: .

      - name: Install dependencies
        run: npm ci

      - name: Generate types
        if: ${{ inputs.publish_types }}
        run: npm run types
      
      - name: Create build
        run: npx @vscode/vsce package --allow-package-all-secrets
        
      - name: Upload build
        id: vsix-upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.package-info.outputs.name }}-pr-build
          path: ./*.vsix

      - name: Set issue number
        id: issue-number
        run: |
          PR_ISSUE_NUMBER=${{ github.event.pull_request.number }}
          ISSUE_NUMBER=${{ github.event.issue.number }}
          echo "::set-output issue-number=value::${PR_ISSUE_NUMBER:-$ISSUE_NUMBER}"

      - name: Find Comment
        if: github.event.pull_request
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ steps.issue-number.outputs.value }}
          comment-author: 'github-actions[bot]'
          body-includes: new build is available

      - name: Post comment
        if: steps.fc.outputs.comment-id == ''
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 A new build is available for this PR based on ${{ github.event.pull_request.head.sha }}.\n * [Download here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.vsix-upload.outputs.artifact-id }})\n* [Read more about how to test](https://github.com/codefori/.github/blob/main/.github/pr_testing_template.md)'            })

      - name: Update comment
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v1
        with:
          edit-mode: replace
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body: |
            👋 A new build is available for this PR based on ${{ github.event.pull_request.head.sha }}.

            * [Download here.](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/${{ steps.vsix-upload.outputs.artifact-id }})
            * [Read more about how to test](https://github.com/codefori/.github/blob/main/.github/pr_testing_template.md)
